### ISSUE TITLE
Prometheus performance

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#293] opened 2018-08-16 22:26 UTC
The production instance of prometheus has been running queries more slowly lately and crashing recently.

We've manually increased ram to 18G and k8s alloc to 25G.

Pending monitoring now.

**Comment by stephen-soltesz** [comment] 2018-08-17 15:12
```
               "-storage.local.index-cache-size.fingerprint-to-metric=104857600",
               "-storage.local.index-cache-size.fingerprint-to-timerange=52428800",
               "-storage.local.index-cache-size.label-name-to-label-values=104857600",
               "-storage.local.index-cache-size.label-pair-to-fingerprints=20971520",
```

**Comment by kokosta** [comment] 2018-08-17 15:13
Duplicate of https://github.com/m-lab/dev-tracker/issues/82

**Closed** 2018-08-17 15:12 UTC
Labels: Sprint 14
