### ISSUE TITLE
ParserDailyVolumeTooLow is an alert that fires spuriously

### ISSUE THREAD

**Issue by pboothe** [m-lab/prometheus-support#165] opened 2018-01-08 22:16 UTC
ParserDailyVolumeTooLow fires spuriously and this is bad. We should figure out an alert that reflects our worries and sensibilities without being spammy, and replace ParserDailyVolumeTooLow with that alert.

**Comment by stephen-soltesz** [comment] 2018-01-08 23:01
For one idea on how to address the mask periods where we get flaky alerts like this see : https://github.com/m-lab/scraper/issues/218#issuecomment-354139011

**Comment by pboothe** [comment] 2018-01-09 22:12
#227 happened because there was a fat tail to the processing time yesterday, which meant that for whatever reason, processing took a little longer yesterday than today, which meant that after processing finished today, the processing volume was too low.

**Comment by gfr10598** [comment] 2018-01-25 16:13
This is fixed by #167.

**Comment by gfr10598** [comment] 2018-01-25 16:14
This is now deployed to production, as of https://github.com/m-lab/prometheus-support/releases/tag/production%2F1.11
There was a real alert yesterday, caused by prometheus collection problems.  It correctly resolved this morning.

**Closed by gfr10598** 2018-01-25 16:14 UTC
